# SPDX-License-Identifier: GPL-3.0-only

from .anima_loader import (
    NODE_CLASS_MAPPINGS as LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_NAME_MAPPINGS,
)
from .anima_prompt_saver import (
    NODE_CLASS_MAPPINGS as SAVER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAVER_DISPLAY_NAME_MAPPINGS,
)
from .anima_sampler import (
    NODE_CLASS_MAPPINGS as SAMPLER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **LOADER_CLASS_MAPPINGS,
    **SAVER_CLASS_MAPPINGS,
    **SAMPLER_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **LOADER_DISPLAY_NAME_MAPPINGS,
    **SAVER_DISPLAY_NAME_MAPPINGS,
    **SAMPLER_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
