# SPDX-License-Identifier: GPL-3.0-only

from .anima_loader import (
    NODE_CLASS_MAPPINGS as LOADER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_NAME_MAPPINGS,
)
from .anima_prompt_saver import (
    NODE_CLASS_MAPPINGS as SAVER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAVER_DISPLAY_NAME_MAPPINGS,
)
from .anima_sampler import (
    NODE_CLASS_MAPPINGS as SAMPLER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAMPLER_DISPLAY_NAME_MAPPINGS,
)
from .dynamic_text_hub import (
    NODE_CLASS_MAPPINGS as TEXT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_NAME_MAPPINGS,
)
from .latent_upscale_with_vae_by import (
    NODE_CLASS_MAPPINGS as LATENT_UPSCALE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LATENT_UPSCALE_DISPLAY_NAME_MAPPINGS,
)
from .schedule_loras_two_text import (
    NODE_CLASS_MAPPINGS as SCHEDULE_LORAS_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SCHEDULE_LORAS_DISPLAY_NAME_MAPPINGS,
)
from .torn_edge_lines import (
    NODE_CLASS_MAPPINGS as TORN_EDGE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TORN_EDGE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **LOADER_CLASS_MAPPINGS,
    **SAVER_CLASS_MAPPINGS,
    **SAMPLER_CLASS_MAPPINGS,
    **TEXT_CLASS_MAPPINGS,
    **LATENT_UPSCALE_CLASS_MAPPINGS,
    **SCHEDULE_LORAS_CLASS_MAPPINGS,
    **TORN_EDGE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **LOADER_DISPLAY_NAME_MAPPINGS,
    **SAVER_DISPLAY_NAME_MAPPINGS,
    **SAMPLER_DISPLAY_NAME_MAPPINGS,
    **TEXT_DISPLAY_NAME_MAPPINGS,
    **LATENT_UPSCALE_DISPLAY_NAME_MAPPINGS,
    **SCHEDULE_LORAS_DISPLAY_NAME_MAPPINGS,
    **TORN_EDGE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
